---
categories:
  Runway:
    components:
      - Button
      - Svg
      - Typography
  Misc:
    components:
      - Alert
      - Spinner
      - Modal
      - Glyph
      - Avatar
      - ProgressBar
      - Stepper
  Forms:
    isFolder: true
    components:
      - FormError
      - FormLabel
      - TextInput
      - TextArea
      - Select
      - OptionLabel
      - Radio
      - Checkbox
  Cards:
    isFolder: true
    components:
      - CardHeading
      - CardBody
      - CardFooter
      - Notification
      - DetailsCard
  Layout:
    isFolder: true
    components:
      - Container
      - Sidebar
      - Footer

components:
  Button: {}
  Svg: {}
  Typography: {}
  Alert: {}
  Spinner: {}
  Modal: {}
  Glyph: {}
  Avatar: {}
  ProgressBar: {}
  Stepper: {}
  FormError: {}
  FormLabel: {}
  TextInput: {}
  TextArea: {}
  Select: {}
  OptionLabel: {}
  Radio: {}
  Checkbox: {}
  CardHeading: {}
  CardBody: {}
  CardFooter: {}
  Container: {}
  Sidebar: {}
  Footer: {}
  Notification: {}
  DetailsCard: {}
